/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.allen.capturewebdata;

import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.AbstractButton;
import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.WindowConstants;


/**
 *
 * @author allv
 */
public class MyFrame extends JFrame {
	
	private MyThread t;
	
	private enum MailBox {
		MailBox_126("126.com","smtp.126.com"),MailBox_163("163.com","smtp.126.com");
		private MailBox(String displayValue,String smtp) { 
			this.smtp = smtp;
			this.displayValue = displayValue;
		}
		private String smtp;
		private String displayValue;
		
		@Override
		public String toString() {
			return this.displayValue;
		}
		
		public String getSmtp() {
			return this.smtp;
		}
	}

    /**
     * Creates new form MyFrame
     */
    public MyFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new JLabel();
        jPanel1 = new JPanel();
        jLabel2 = new JLabel();
        jLabel3 = new JLabel();
        jLabel4 = new JLabel();
        tfUserName = new JTextField();
        jPasswordField1 = new JPasswordField();
        jComboBox1 = new JComboBox();
        jLabel5 = new JLabel();
        jPanel2 = new JPanel();
        jLabel6 = new JLabel();
        tfReceipient = new JTextField();
        stopButton = new JButton();
        startButton = new JButton();
        jScrollPane1 = new JScrollPane();
        jTextArea1 = new JTextArea();
        jPanel3 = new JPanel();
        lbProxy = new JLabel();
        lbProxyName = new JLabel();
        lbProxyIP = new JLabel();
        lbProxyPass = new JLabel();
        lbProxyPort = new JLabel();
        tfProxyIP = new JTextField();
        tfProxyPort = new JTextField();
        tfProxyName = new JTextField();
        tfProxyPass = new JTextField();
        lbGoodsName  =new JLabel();
        tfGoodsName = new JTextField();
        

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aptamil");
        setResizable(true);

        jLabel1.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel1.setText("爱他美奶粉监听程序");
        jLabel1.setHorizontalTextPosition(SwingConstants.CENTER);

        jPanel1.setBorder(BorderFactory.createEtchedBorder());

        jLabel2.setText("用户名:");

        jLabel3.setText("密码:");

        jLabel4.setText("邮箱:");

        tfUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });

        jComboBox1.addItem(MailBox.MailBox_126);
        jComboBox1.addItem(MailBox.MailBox_163);

        jLabel5.setText("发件人");

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfUserName, GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                            .addComponent(jPasswordField1)
                            .addComponent(jComboBox1, GroupLayout.PREFERRED_SIZE, 86, GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel5)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfUserName, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jPasswordField1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(BorderFactory.createEtchedBorder());

        jLabel6.setText("收件人:");

        stopButton.setText("停止");
        stopButton.addActionListener(new ActionListener() {

			public void actionPerformed(ActionEvent e) {
				stopButtonActionPerformed(e);
			}
			
		});

        startButton.setText("开始");
        startButton.addActionListener(new ActionListener() {
        	
			public void actionPerformed(ActionEvent e) {
				startButtonActionPerformed(e);
			}
		});
        
        lbGoodsName.setText("商品名称关键字:");

        GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(stopButton)
                        .addGap(43, 43, 43)
                        .addComponent(startButton))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(tfReceipient, GroupLayout.PREFERRED_SIZE, 133, GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108)
                        .addComponent(lbGoodsName)
                        .addGap(18, 18, 18)
                        .addComponent(tfGoodsName, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfReceipient, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbGoodsName)
                    .addComponent(tfGoodsName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(stopButton)
                    .addComponent(startButton))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setWrapStyleWord(false);
        jTextArea1.setLineWrap(false);
        jScrollPane1.setViewportView(jTextArea1);
        
        
        jPanel3.setBorder(BorderFactory.createEtchedBorder());

        lbProxy.setText("网络代理设置");

        lbProxyIP.setText("地址:");

        lbProxyPort.setText("端口:");

        lbProxyName.setText("用户名:");

        lbProxyPass.setText("密码:");
        
        GroupLayout jPanel3Layout = new GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(lbProxyIP)
                            .addComponent(lbProxyPort)
                            .addComponent(lbProxyName)
                            .addComponent(lbProxyPass))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tfProxyName, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                            .addComponent(tfProxyPort, GroupLayout.Alignment.LEADING)
                            .addComponent(tfProxyIP, GroupLayout.Alignment.LEADING)
                            .addComponent(tfProxyPass)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbProxy)))
                .addGap(126, 126, 126))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbProxy)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(lbProxyIP)
                    .addComponent(tfProxyIP, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(lbProxyPort)
                    .addComponent(tfProxyPort, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(lbProxyName)
                    .addComponent(tfProxyName, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(lbProxyPass)
                    .addComponent(tfProxyPass, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(255, 255, 255)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void stopButtonActionPerformed(ActionEvent e) {
    	jTextArea1.setText("");
    	jTextArea1.append("你已经停止监控了!");
    	if(t != null ) {
    		t.interrupt();
    		t= null;
    		enableComponent();
    	}
	}

	private void enableComponent() {
		startButton.setEnabled(true);
		tfUserName.setEnabled(true);
		jPasswordField1.setEnabled(true);
		jComboBox1.setEnabled(true);
		tfProxyIP.setEnabled(true);
		tfProxyName.setEnabled(true);
		tfProxyPass.setEnabled(true);
		tfProxyPort.setEnabled(true);
		tfReceipient.setEnabled(true);
		tfGoodsName.setEnabled(true);
	}

	private void startButtonActionPerformed(ActionEvent e) {
		jTextArea1.setText(null);
    	boolean flag = checkAllFieldsNotEmpty();
    	if(!flag) {
    		jTextArea1.append("用户名,密码,收件人,商品名称不能为空!");
    	}else{
    		startCheckMilk();
    		disableComponent();
    	}
	}

	private void disableComponent() {
		startButton.setEnabled(false);
		tfUserName.setEnabled(false);
		jPasswordField1.setEnabled(false);
		jComboBox1.setEnabled(false);
		tfProxyIP.setEnabled(false);
		tfProxyName.setEnabled(false);
		tfProxyPass.setEnabled(false);
		tfProxyPort.setEnabled(false);
		tfReceipient.setEnabled(false);
		tfGoodsName.setEnabled(false);
	}

	private void startCheckMilk() {
		t = new MyThread();
		t.setSmtpServer(((MailBox)this.jComboBox1.getSelectedItem()).getSmtp());
		t.setUser(this.tfUserName.getText());
		t.setPwd(new String(this.jPasswordField1.getPassword()));
		t.setTo(this.tfReceipient.getText());
		t.setConsole(jTextArea1);
		t.setProxyIP(tfProxyIP.getText());
		t.setProxyName(tfProxyName.getText());
		t.setProxyPass(tfProxyPass.getText());
		t.setProxyPort(tfProxyPort.getText());
		t.setGoods(tfGoodsName.getText());
		jTextArea1.append("开始监控了!有货就会发信息到你邮箱,请不要关闭程序......");
		t.start();
	}

	private boolean checkAllFieldsNotEmpty() {
		if(tfUserName.getText() == null || tfUserName.getText().equals("")) {
			return false;
		}
		
		if(jPasswordField1.getPassword() == null || jPasswordField1.getPassword().length <= 0) {
			return false;
		}
		
		if(tfReceipient.getText() == null || tfReceipient.getText().equals("")) {
			return false;
		}
		
		if(tfGoodsName.getText() == null || tfGoodsName.getText().equals("")) {
			return false;
		}
		
		return true;
	}

	private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    }                                               

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify                     
    private JButton stopButton;
    private JButton startButton;
    private JComboBox jComboBox1;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JPanel jPanel1;
    private JPanel jPanel2;
    private JPasswordField jPasswordField1;
    private JScrollPane jScrollPane1;
    private JTextArea jTextArea1;
    private JTextField tfUserName;
    private JTextField tfReceipient;
    private JTextField tfProxyName;
	private JTextField tfProxyPort;
	private JTextField tfProxyIP;
	private JTextField tfProxyPass;
	private JLabel lbProxy;
	private JLabel lbProxyPass;
	private JLabel lbProxyName;
	private JLabel lbProxyPort;
	private JLabel lbProxyIP;
    private JPanel jPanel3;
    private JLabel lbGoodsName;
	private JTextField tfGoodsName;
    // End of variables declaration                   
}
